"""Initial user authentication and multi-user isolation migration

Revision ID: 001_initial_auth
Revises:
Create Date: 2025-01-17 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_auth'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create users table
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('organization', sa.String(length=255), nullable=True),
        sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('verification_token', sa.String(length=255), nullable=True),
        sa.Column('verification_expires', sa.DateTime(timezone=True), nullable=True),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reset_token', sa.String(length=255), nullable=True),
        sa.Column('reset_expires', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'])
    op.create_index('ix_users_username', 'users', ['username'])

    # Create refresh_tokens table
    op.create_table(
        'refresh_tokens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('token', sa.String(length=500), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refresh_tokens_user_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )
    op.create_index('ix_refresh_tokens_token', 'refresh_tokens', ['token'])
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'])

    # Add user_id column to labware table
    op.add_column('labware', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('labware', sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false'))
    op.create_foreign_key('labware_user_id_fkey', 'labware', 'users', ['user_id'], ['id'])

    # Update existing labware to be shared defaults
    op.execute("UPDATE labware SET is_default = true WHERE user_id IS NULL")

    # Create a default admin user first if it doesn't exist
    from datetime import datetime
    op.execute("""
        INSERT INTO users (email, username, password_hash, role, is_active, is_verified, is_superuser, created_at, updated_at)
        SELECT 'admin@hamilton.local', 'admin', '$2b$12$dummy.hash.for.migration', 'ADMIN', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@hamilton.local')
    """)

    # Add user_id foreign key to user_settings (replacing user_id string)
    # First, we need to migrate existing user_settings data
    op.execute("UPDATE user_settings SET user_id = '1' WHERE user_id = 'default'")

    # Add new user_id column (temporary - we'll rename in a moment)
    op.add_column('user_settings', sa.Column('new_user_id', sa.Integer(), nullable=True))

    # Copy data from old user_id to new_user_id
    op.execute("UPDATE user_settings SET new_user_id = CAST(user_id AS INTEGER) WHERE user_id ~ '^[0-9]+$'")

    # Drop old user_id column and rename new one
    op.drop_column('user_settings', 'user_id')
    op.alter_column('user_settings', 'new_user_id', nullable=False)

    # Rename the column back to user_id
    op.execute("ALTER TABLE user_settings RENAME COLUMN new_user_id TO user_id")

    # Add foreign key constraint
    op.create_foreign_key('user_settings_user_id_fkey', 'user_settings', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign keys
    op.drop_constraint('user_settings_user_id_fkey', 'user_settings', type_='foreignkey')
    op.drop_constraint('labware_user_id_fkey', 'labware', type_='foreignkey')
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')

    # Revert user_settings user_id changes
    op.add_column('user_settings', sa.Column('user_id_old', sa.String(length=100), nullable=False))
    op.execute("UPDATE user_settings SET user_id_old = CAST(user_id AS VARCHAR)")
    op.drop_column('user_settings', 'user_id')
    op.alter_column('user_settings', 'user_id_old', nullable=False, server_default='default')

    # Revert labware changes
    op.drop_column('labware', 'is_default')
    op.drop_column('labware', 'user_id')

    # Drop tables
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')

    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')

    # ### end Alembic commands ###